# Generated by Django 5.1.7 on 2025-04-09 13:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="materials.course",
                verbose_name="Подписка на курс",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="materials.lesson",
            ),
        ),
    ]
